# Generated by Django 5.1.4 on 2024-12-09 05:55

import django.db.models.deletion
import propiedades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10, validators=[propiedades.models.validate_phone])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10, validators=[propiedades.models.validate_phone])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[propiedades.models.validate_price])),
                ('descripcion', models.TextField(blank=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.agente')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[propiedades.models.validate_price])),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.inmueble')),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.prospecto')),
            ],
        ),
    ]
