# Generated by Django 5.1.4 on 2024-12-09 06:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import propiedades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='numero_documento',
            field=models.CharField(default=0, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6, 'Número de documento debe tener al menos 6 caracteres')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agente',
            name='tipo_documento',
            field=models.CharField(choices=[('CI', 'Carnet de Identidad'), ('CE', 'Cédula de Extranjería'), ('PP', 'Pasaporte')], default='Carnet de Identidad', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='status',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido')], default='DISPONIBLE', max_length=15),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='type',
            field=models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('OFICINA', 'Oficina'), ('TERRENO', 'Terreno')], default='Casa', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prospecto',
            name='interested_properties',
            field=models.ManyToManyField(blank=True, to='propiedades.inmueble'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='agente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='propiedades.agente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agente',
            name='telefono',
            field=models.CharField(max_length=8, validators=[propiedades.models.validate_phone]),
        ),
    ]
