# Generated by Django 5.1.4 on 2024-12-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_agente_numero_documento_agente_tipo_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='type',
            new_name='tipo_inmueble',
        ),
    ]
